var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var jsonArr=[],jsonTitleArr=[],gNoArr=[],json="",gId="",gTitle="",gQuiz="",gAnswer="",gLang="",gVoice="",gInputType="",gDescription="",gChoiceArr=[],gNextNo="",startTime,endTime,gAiconNormal="",gAiconSmile="",gAiconAngry="",gAiconSadness="",gQuizMax="";
function setJsonList(){jsonArr.length=0;jsonTitleArr.length=0;getJson("questlist.json");for(i=0;i<json.length;i++)0==i?(gAiconNormal=json[i].aiconNormal,gAiconSmile=json[i].aiconSmile,gAiconAngry=json[i].aiconAngry,gAiconSadness=json[i].aiconSadness):(jsonArr.push(json[i].Json),jsonTitleArr.push(json[i].Title))}
function setInitialValue(){gDescription=gInputType=gVoice=gLang=gAnswer=gQuiz=gId="";gChoiceArr.length=0;document.getElementById("QuizArea").innerHTML="";document.getElementById("AnswerArea").innerHTML="";startTime=Date.now();endTime=""}
function quizFlow(a){json="";gNoArr.length=0;getJson(jsonArr[a]);gQuizMax=json.length-1;for(a=1;a<json.length;a++)gNoArr.push(a);for(a=gNoArr.length-1;0<=a;a--){var b=Math.floor(Math.random()*(a+1)),c=$jscomp.makeIterator([gNoArr[b],gNoArr[a]]);gNoArr[a]=c.next().value;gNoArr[b]=c.next().value}gNextNo=0;setInitialValue();setZeroCellValue();setZeroQuizArea();setCommandArea("HideAnswerButton");pronounce(gLang,gVoice);document.getElementById("QuizAiconArea").src=gAiconNormal;document.getElementById("AnswerAiconArea").src=
gAiconNormal;document.getElementById("AnswerArea").innerHTML="\u30fb\u30fb\u30fb"}function setCellValue(a){gId=json[a].id;gQuiz=json[a].Quiz;gAnswer=json[a].Answer;gLang=json[a].Lang;gVoice=""==json[a].Voice?json[a].Quiz:json[a].Voice;gInputType=json[a].InputType;gDescription=json[a].Description;for(i=0;i<json[a].Choice.length;i++)gChoiceArr.push(json[a].Choice[i])}
function setZeroCellValue(){gId=json[0].id;gTitle=json[0].Title;gQuiz=json[0].Quiz;gAnswer=json[0].Answer;gLang=json[0].Lang;gVoice=""==json[0].Voice?json[0].Quiz:json[0].Voice;gAiconNormal=json[0].aiconNormal;gAiconSmile=json[0].aiconSmile;gAiconAngry=json[0].aiconAngry;gAiconSadness=json[0].aiconSadness}
function setZeroQuizArea(){var a=""+gQuiz;document.getElementById("QuizArea").innerHTML=a;document.getElementById("AnswerAiconArea").src=gAiconNormal;document.getElementById("AnswerArea").innerHTML="\u2191\u306e\u30dc\u30bf\u30f3\u3092\u30af\u30ea\u30c3\u30af"}
function setQuizArea(){var a="\u3010"+gTitle+"\u3011 ( "+(gNextNo+1)+"/"+gQuizMax+" \uff09<br />";a+=gQuiz;for(var b=gChoiceArr.length-1;0<=b;b--){var c=Math.floor(Math.random()*(b+1)),d=$jscomp.makeIterator([gChoiceArr[c],gChoiceArr[b]]);gChoiceArr[b]=d.next().value;gChoiceArr[c]=d.next().value}a+="<form id='"+gId+"'>";for(b=0;b<gChoiceArr.length;b++)c=gChoiceArr[b].slice(0,1),d=gChoiceArr[b].slice(2),a+="<br /><input type='"+gInputType+"' name='"+gId+"' value='"+c+"'>"+d;a+="</form>";document.getElementById("QuizArea").innerHTML=
a}
function setCommandArea(a){var b="";if("END"!=a){var c="CommandArea";"HideAnswerButton"!=a&&(b+="<a href='#'' class='square_btn' onclick='checkAnswer();'>\u56de\u7b54\u3059\u308b</a><br /><br />");b+="<a href='#'' class='square_btn' onclick='backQuiz();'>\uff1c\u623b\u308b</a> <a href='#'' class='square_btn' onclick='pronounce(gLang,gVoice);'>\u97f3\u58f0</a> <a href='#'' class='square_btn' onclick='nextQuiz();'>\u9032\u3080\uff1e</a><br /><br /><a href='#'' class='square_btn' onclick='showList();'>\u4e00\u89a7\u306b\u623b\u308b</a>"}else c="AnswerArea",
b+="\u7d42\u4e86\u3067\u3059",pronounce("ja",b),document.getElementById("AnswerAiconArea").src=gAiconSmile;b="<p>"+b+"</p>";document.getElementById(c).innerHTML=b}
function checkAnswer(){var a="",b="";endTime=Date.now();for(i=0;i<document.forms[gId].length;i++)document.forms[gId].elements[i].checked&&(a+=document.forms[gId].elements[i].value);if(null!=(new RegExp(gAnswer)).exec(a)){a="\u6b63\u89e3\u3067\u3059";var c=gAiconSmile}else a="\u4e0d\u6b63\u89e3\u3067\u3059",c=gAiconSadness;b+=a+"<BR />"+gDescription;document.getElementById("AnswerAiconArea").src=c;document.getElementById("AnswerArea").innerHTML=b;pronounce("ja",a)}
function showList(){var a="";setJsonList();a+="";for(i=0;i<jsonArr.length;i++)a+=" <a href='#'' class='square_btn' onclick='quizFlow("+i+");'>"+jsonTitleArr[i]+"</a><br />";document.getElementById("QuizAiconArea").src=gAiconNormal;document.getElementById("QuizArea").innerHTML=a;document.getElementById("AnswerAiconArea").src=gAiconNormal;document.getElementById("AnswerArea").innerHTML="\u30ea\u30b9\u30c8\u304b\u3089\u9078\u629e";document.getElementById("CommandArea").innerHTML="<P>\u30fb\u30fb\u30fb</P>"}
function backQuiz(){gNextNo-=2;0>gNextNo&&(gNextNo=0);nextQuiz()}function nextQuiz(){gNextNo<gNoArr.length?(setInitialValue(),setCellValue(gNoArr[gNextNo]),setQuizArea(),setCommandArea("ShowAnswerButton"),pronounce(gLang,gVoice),gNextNo+=1,document.getElementById("AnswerAiconArea").src=gAiconNormal,document.getElementById("AnswerArea").innerHTML="\u30fb\u30fb\u30fb"):setCommandArea("END")}var walkJSON=function walkJSON(a,b){for(var d in a)b(d,a[d]),"object"===typeof a[d]&&walkJSON(a[d],b)};
function getJson(a){var b=new XMLHttpRequest;b.onreadystatechange=function(){4==b.readyState&&200==b.status&&(json=JSON.parse(b.responseText))};b.open("GET",a,!1);b.send(null)}function pronounce(a,b){var c=new SpeechSynthesisUtterance;c.lang=a;c.text=b;c.rate=1;c.pitch=1;speechSynthesis.speak(c)};